import uuid
from django.db import models
from django.contrib.auth.models import User
from datasets.models import Dataset


class AnalysisSession(models.Model):
    """A session of analysis work on a dataset."""

    TYPE_CHOICES = [
        ('eda', 'Exploratory Data Analysis'),
        ('visualization', 'Data Visualization'),
        ('hypothesis', 'Hypothesis Testing'),
        ('ml_model', 'Machine Learning Model'),
        ('dl_model', 'Deep Learning Model'),
        ('sql_query', 'SQL Query'),
        ('general', 'General Analysis'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('running', 'Running'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default='')
    analysis_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name='analyses',
                                null=True, blank=True)
    project = models.ForeignKey('projects.Project', on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='analyses')

    # Input/output
    query = models.TextField(blank=True, default='',
                             help_text='Natural language query or configuration')
    parameters = models.JSONField(default=dict, blank=True)
    result = models.JSONField(default=dict, blank=True)
    code_generated = models.TextField(blank=True, default='',
                                      help_text='Python code generated by agent')
    error_message = models.TextField(blank=True, default='')

    # Task tracking
    celery_task_id = models.CharField(max_length=255, blank=True, default='')
    execution_time = models.FloatField(null=True, blank=True,
                                       help_text='Execution time in seconds')

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Analysis sessions'

    def __str__(self):
        return f"{self.name} ({self.analysis_type})"


class Visualization(models.Model):
    """Stored visualization outputs."""

    CHART_TYPES = [
        ('kde', 'KDE Plot'),
        ('histogram', 'Histogram'),
        ('scatter', 'Scatter Plot'),
        ('bar', 'Bar Chart'),
        ('line', 'Line Chart'),
        ('heatmap', 'Heatmap'),
        ('box', 'Box Plot'),
        ('violin', 'Violin Plot'),
        ('pie', 'Pie Chart'),
        ('pair', 'Pair Plot'),
        ('custom', 'Custom'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    chart_type = models.CharField(max_length=20, choices=CHART_TYPES)
    description = models.TextField(blank=True, default='')

    analysis = models.ForeignKey(AnalysisSession, on_delete=models.CASCADE,
                                 related_name='visualizations', null=True, blank=True)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE,
                                related_name='visualizations', null=True, blank=True)

    # Chart configuration
    config = models.JSONField(default=dict, blank=True,
                              help_text='Plotly/chart configuration')
    plotly_json = models.JSONField(default=dict, blank=True,
                                   help_text='Plotly figure JSON')

    # Image output
    image = models.ImageField(upload_to='visualizations/', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.chart_type})"


class MLModel(models.Model):
    """Trained ML model records."""

    MODEL_TYPES = [
        # Traditional ML
        ('logistic_regression', 'Logistic Regression'),
        ('random_forest', 'Random Forest'),
        ('xgboost', 'XGBoost'),
        ('svm', 'Support Vector Machine'),
        ('neural_network', 'Neural Network'),
        ('decision_tree', 'Decision Tree'),
        ('knn', 'K-Nearest Neighbors'),
        ('gradient_boosting', 'Gradient Boosting'),
        ('linear_regression', 'Linear Regression'),
        # Deep Learning
        ('cnn', 'Convolutional Neural Network'),
        ('rnn', 'Recurrent Neural Network'),
        ('lstm', 'Long Short-Term Memory'),
        ('gru', 'Gated Recurrent Unit'),
        ('transformer', 'Transformer'),
        ('autoencoder', 'Autoencoder'),
        ('gan', 'Generative Adversarial Network'),
        ('mlp', 'Multi-Layer Perceptron'),
        ('resnet', 'ResNet'),
        ('custom', 'Custom Model'),
    ]

    TASK_TYPES = [
        ('classification', 'Classification'),
        ('regression', 'Regression'),
        ('clustering', 'Clustering'),
        ('image_classification', 'Image Classification'),
        ('text_classification', 'Text Classification'),
        ('sequence_prediction', 'Sequence Prediction'),
        ('anomaly_detection', 'Anomaly Detection'),
        ('generative', 'Generative'),
    ]

    FRAMEWORK_CHOICES = [
        ('sklearn', 'Scikit-learn'),
        ('pytorch', 'PyTorch'),
        ('tensorflow', 'TensorFlow'),
        ('auto', 'Auto Select'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    model_type = models.CharField(max_length=30, choices=MODEL_TYPES)
    task_type = models.CharField(max_length=30, choices=TASK_TYPES, default='classification')
    framework = models.CharField(max_length=20, choices=FRAMEWORK_CHOICES, default='sklearn')
    description = models.TextField(blank=True, default='')

    dataset = models.ForeignKey(Dataset, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='ml_models')
    analysis = models.ForeignKey(AnalysisSession, on_delete=models.SET_NULL,
                                 null=True, blank=True, related_name='ml_models')

    # Model details
    target_column = models.CharField(max_length=255, blank=True, default='')
    feature_columns = models.JSONField(default=list, blank=True)
    hyperparameters = models.JSONField(default=dict, blank=True)

    # Deep learning specific
    epochs = models.IntegerField(null=True, blank=True)
    batch_size = models.IntegerField(null=True, blank=True)
    learning_rate = models.FloatField(null=True, blank=True)

    # Results
    metrics = models.JSONField(default=dict, blank=True,
                               help_text='accuracy, precision, recall, f1, etc.')
    confusion_matrix = models.JSONField(default=dict, blank=True)
    feature_importance = models.JSONField(default=dict, blank=True)
    training_history = models.JSONField(default=dict, blank=True)

    # Model file
    model_file = models.FileField(upload_to='ml_models/', null=True, blank=True)
    model_size = models.BigIntegerField(null=True, blank=True)

    # Code
    code_generated = models.TextField(blank=True, default='')

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.model_type}) - {self.task_type}"


class HypothesisTest(models.Model):
    """Hypothesis testing results."""

    TEST_TYPES = [
        ('t_test', 'T-Test'),
        ('chi_square', 'Chi-Square Test'),
        ('anova', 'ANOVA'),
        ('mann_whitney', 'Mann-Whitney U Test'),
        ('pearson', 'Pearson Correlation'),
        ('spearman', 'Spearman Correlation'),
        ('shapiro', 'Shapiro-Wilk Normality Test'),
        ('custom', 'Custom Test'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    test_type = models.CharField(max_length=20, choices=TEST_TYPES)

    dataset = models.ForeignKey(Dataset, on_delete=models.SET_NULL, null=True, blank=True)
    analysis = models.ForeignKey(AnalysisSession, on_delete=models.SET_NULL,
                                 null=True, blank=True, related_name='hypothesis_tests')

    null_hypothesis = models.TextField(blank=True, default='')
    alt_hypothesis = models.TextField(blank=True, default='')
    significance_level = models.FloatField(default=0.05)

    # Results
    test_statistic = models.FloatField(null=True, blank=True)
    p_value = models.FloatField(null=True, blank=True)
    reject_null = models.BooleanField(null=True, blank=True)
    conclusion = models.TextField(blank=True, default='')
    details = models.JSONField(default=dict, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.test_type})"
